Merge List

In [2]:
a =['a', 'b', 'c'] + [1, 2, 3]
a

['a', 'b', 'c', 1, 2, 3]

Create an array

In [5]:
import numpy as np
r = np.array([[0, 1, 2, 3, 4 ,5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35]])
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Slice an array

In [8]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [9]:
r[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [10]:
r[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [11]:
r[::7]

array([[0, 1, 2, 3, 4, 5]])

In [14]:
r[[2,3],[2,3]]

array([14, 21])

In [15]:
r[::2,::2]

array([[ 0,  2,  4],
       [12, 14, 16],
       [24, 26, 28]])

In [16]:
r[2::2,2::2]

array([[14, 16],
       [26, 28]])

In [17]:
r[2:4,2:4]

array([[14, 15],
       [20, 21]])